### ISSUE TITLE
Image for building rpm

### ISSUE THREAD

**Issue by ibanezn04** [hseeberger/scala-sbt#112]
Hi, i'm wondering if there is an image that i could use to build rpm using sbt native packager plugin? I thought ```hseeberger/scala-sbt:11.0.2-oraclelinux7_1.3.12_2.13.2``` would work because it's red hat based distro, but it doesn't:
```[error] java.io.IOException: Cannot run program "rpmbuild" (in directory "/opt/teamcity-agent/work/568b3d2ec6bdf2ae/my_project/target/rpm/SPECS"): error=2, No such file or directory```

**Comment by hseeberger** [comment]
No idea, sorry.
