### ISSUE TITLE
add again rpm (for rpmbuild used in sbt native packager)

### ISSUE THREAD

**Issue by gbrd** [hseeberger/scala-sbt#134]
apt-get install rpm was removed (accidentally along with apt-get install sbt ?)

**Comment by francisdb** [comment]
we are no longer installing through apt/rpm
mainly because of https://github.com/sbt/sbt/releases/tag/v1.4.9 mention that the packages are no longer provided as jcenter is going down

Do you have problems starting scala or sbt in the image?

**Comment by gbrd** [comment]
When running 
```
sbt rpm:packageBin 
```
rpmbuild binary is required in the image

**Comment by francisdb** [comment]
You can install that yourself? Must be that some base Image we build on no longer provides this. I already saw that some switched from `yum` to `microdnf` before we switched to installing using the sbt `.tar.gz` archive.

I don't think this is something that needs solving here. The purpose of these images is providing scala and sbt which is working as expected.

What image are you using?

**Comment by francisdb** [comment]
Have you tried this?

```
microdnf -y install rpm-build
```

**Comment by gbrd** [comment]
Thanks for your reactivity !

It worked before and it was useful.
I need to build a RPM in my ci pipeline (that uses scala-sbt image) and I need to do that using a sbt command thus I need rpmbuild binary in the same image than sbt. 

I cannot use one separate image/ci job to launch rpmbuild because is is launched by sbt (with sbt native packager plugin)

I would like to avoid maintaining my own image (and this is the purpose of scala-sbt image to "pool" this effort)

I could install it each time in the build job but it would be inefficient. 

I don't see how micodnf or yum could help me ? (maybe i misunderstood) I just need rpmbuild binary in the image for my build process, I don't need to find another package manager. 

I'm not sur to understand the problem : sbt is not available in deb repository but it "rpm" package is and is contains rpmbuild binary.
the lines
```
apt-get update &&
apt-get install sbt rpm -y
```
were removed but the intention was to stop installing sbt package using apt-get command (and use tag.gz instead). The intention was not to stop install "rpm" package itself ?

**Comment by gbrd** [comment]
To be clear, my suggestion is to add again (in debian dockerfile)
```
apt-get update &&
apt-get install rpm -y
```
This will install "rpm" debian package (containing rpmbuild that allows to build rpm) but not sbt. rpm package is available in debian repository.

**Comment by francisdb** [comment]
I understand now, can you not do `apt-get install rpm -y` as fist thing in your ci job? It's quite a waste to make the image bigger just for this specific case?

**Comment by francisdb** [comment]
anyway, since this is a regression I will put it back
I see it was previously added in #114

**Comment by francisdb** [comment]
@gbrd let me know if this issue is fixed, thanks for pointing to the regression.

**Comment by gbrd** [comment]
It works ! thanks a lot. :)
