### ISSUE TITLE
Support for Java 16

### ISSUE THREAD

**Issue by therockstorm** [hseeberger/scala-sbt#138]
Are you open to adding support for Java 16 to the build matrix? The `baseImageTag` would be `16-jdk-buster`.

**Comment by francisdb** [comment]
My idea was supporting lts + latest and greatest. We would then replace 15 with 16. On the other hand maybe we could stick to all the versions that still get support. I wonder if docker hub has some kind of limit in the number of images we can publish.

**Comment by francisdb** [comment]
Will see if anybody complains about jdk15 builds no longer getting new images

**Comment by francisdb** [comment]
images pushed and available here:
https://hub.docker.com/r/hseeberger/scala-sbt/tags?page=1&ordering=last_updated&name=16_

**Comment by therockstorm** [comment]
Thanks!
