### ISSUE TITLE
Multi-arch support (buildx)

### ISSUE THREAD

**Issue by mfirry** [hseeberger/scala-sbt#153]
Hi, thanks so much for this. I was wondering if there is any plan to have multi-arch support (not super familiar with this, I've just discovered [here](https://docs.docker.com/desktop/multi-arch/#multi-arch-support-on-docker-desktop)) for `arm` (Apple M1) compatibility (without rosetta).

Thanks

**Comment by francisdb** [comment]
Also not familiar with this, looks like github does not yet provide M1 build hosts
https://github.com/actions/virtual-environments/issues/2187

Any info on what we need to do to implement this or a pr would be welcome.

**Comment by francisdb** [comment]
And there is a buildx action available

https://github.com/marketplace/actions/docker-setup-buildx

**Comment by westwater** [comment]
You can build arm64v8 images on Intel 64-bit hosts

I also needed this support so copied most of the owners dockerfile to publish multi-arch (amd64/arm64) images for scala-sbt - this can be found here https://hub.docker.com/r/westwater/scala-sbt/tags?page=1&ordering=last_updated

This is only temporary while I wait for the owner to publish his own

**Comment by francisdb** [comment]
Great. Any instructions on how to build these would be welcome. That should help me get started tweaking the GitHub actions.

**Comment by westwater** [comment]
I used docker's buildx utility to publish multi-arch images ([this](https://docs.docker.com/desktop/multi-arch/) doc explains it really well)
```
docker buildx create --use // to create the buildkit daemon and use the builder
docker buildx build --platform linux/amd64,linux/arm64 -t ${IMAGE_TAG} --push .
```

**Comment by francisdb** [comment]
finally got this working, see https://hub.docker.com/r/hseeberger/scala-sbt/tags?page=1&ordering=last_updated

@mfirry @westwater please let me know if the image works as expected
