### ISSUE TITLE
graalvm images are bloated

### ISSUE THREAD

**Issue by jrudolph** [hseeberger/scala-sbt#154]
Partly because of the base image but also because `chown -R /opt` creates a new layer that reintroduces 900MB of files. (The numbers shown on docker hub are only half the size because of compression.)

**Comment by francisdb** [comment]
Any suggestions?

**Comment by jrudolph** [comment]
Maybe:

 * Don't touch permissions if not really necessary
 * Avoid official graalvm image and just start from a simple image and unpack graalvm

**Comment by francisdb** [comment]
I guess that `/opt` stuff is from the time we were using the .deb/rpm

**Comment by francisdb** [comment]
@jrudolph mind to have a look at the linked pr?
Building a custom graal image is a bit out of the scope of this project but a pr is of course welcome.

**Comment by francisdb** [comment]
@jrudolph never mind, not too much in there anyway

**Comment by francisdb** [comment]
Thanks for reporting this @jrudolph
Let me know if you want me to reconsider that custom graalvm image ;-)
