### ISSUE TITLE
[Internal] load build context

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [hseeberger/scala-sbt#162]
I have a multistage Docker build; here is the relevant part of that file.

```
FROM node:14 AS vue-builder
RUN mkdir -p /usr/client-ui
WORKDIR /usr/client-ui
COPY client/ui/package.json /usr/client-ui/
RUN npm install
COPY client/ui /usr/client-ui
RUN npm run build

FROM hseeberger/scala-sbt:11.0.11_1.5.3_2.13.6 AS scala-builder
RUN mkdir -p /usr
WORKDIR /usr
COPY . /usr
COPY --from=vue-builder /usr/client-ui/dist ./public/
RUN sbt client/dist

...
```

but running it on Windows produces the following error:

```
error from sender: open client\target\streams\_global\assemblyOption\_global\streams\assembly\0a94896a5ea2f8e42101b8156972ca3f4522a922_5d9f3d441f99d721b957e3497f0a6465c764fad4_da39a3ee5e6b4b0d3255bfef95601890afd80709\com\fasterxml\jackson\databind: Access is denied.
```

Incidentally running it within WSL seems to work.

I've checked that it's definitely `hseeberger/scala-sbt` that's causing the error and I've tried multiple other tags with the same result. Any idea what's happening?

**Comment by PaperPlaneSoftware** [comment]
Turns out I' an idiot and I hadn't ignored the target folder when copying files to the image. Sorry for the noise!

**Comment by francisdb** [comment]
np, looks like you were in need of some [Rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging)
