### ISSUE TITLE
Tag images in docker hub

### ISSUE THREAD

**Issue by palmerabollo** [hseeberger/scala-sbt#17]
Could you start tagging the images in dockerhub, so we can avoid using "latest"? (to guarantee reproducibility when we create images from yours). Thanks.

**Comment by hseeberger** [comment]
I guess I could, but I also could need some help with it. Would you be interested in collaborating?

**Comment by digitalLumberjack** [comment]
Hi, thanks for the work here.

I need tags too, i can help if needed.

**Comment by hseeberger** [comment]
@digitalLumberjack Great! Please PR.

**Comment by digitalLumberjack** [comment]
It's just a matter of semantic versioning and docker hub configuration.

The docker hub build must be configured to build on tags like this one:
![capture d ecran de 2017-07-09 12-39-58](https://user-images.githubusercontent.com/1128425/27993153-f305a386-64a3-11e7-8df2-3c00ee99d919.png)


And you will choose to tag your github repo with semantic version:
- detailed : `jdk8-scala2.12.2-sbt0.13.7`
- just on scala version : `v2.12.2`
- or with your specific versioning

**Comment by hseeberger** [comment]
Thanks! That seems easy to do.

**Comment by hseeberger** [comment]
Here you are: scala-2.12.2-sbt-0.13.15

**Comment by digitalLumberjack** [comment]
Thanks :)
