### ISSUE TITLE
caching of jars

### ISSUE THREAD

**Issue by fommil** [hseeberger/scala-sbt#20]
if you want the sbt (and scala-library) jars to be downloaded in this image, you'd be best doing something like https://github.com/ensime/ensime-docker/blob/v1.x/Dockerfile#L48-L55

```
  mkdir -p project src/main/scala &&\
  touch src/main/scala/scratch.scala &&\
  for SBT_VERSION in $SBT_VARIANTS ; do\
    echo "sbt.version=$SBT_VERSION" > project/build.properties &&\
    for SCALA_VERSION in $SCALA_VARIANTS ; do\
      sbt ++$SCALA_VERSION clean updateClassifiers compile ;\
    done ;\
  done
```

**Comment by fommil** [comment]
FYI https://github.com/fommil/docker-openjdk-sbt

I'm trying out gitlab and it makes sense to have a base image I'll use there (which is trimmer than the huge ensime one...)

**Comment by hseeberger** [comment]
Thanks. But this image is single Scala and single sbt version.

**Comment by fommil** [comment]
then you just use one value in each of those settings. You'll get the compiler bridge built for you this way.
