### ISSUE TITLE
Push 1.0.3 version to Dockerhub

### ISSUE THREAD

**Issue by leonardehrenfried** [hseeberger/scala-sbt#26]
Hi,

according to https://hub.docker.com/r/hseeberger/scala-sbt/tags/ there is no 1.0.3 tag on Dockerhub.

Would you be able to push it there?

Thanks!

**Comment by hseeberger** [comment]
Good catch. There was a build error which is related to an sbt issue: https://github.com/sbt/sbt/issues/3697.

Unfortunately I don't have the cycles for a workaround, so there won't be 1.0.3 version.
