### ISSUE TITLE
Compile may fail due to character limit imposed by Docker

### ISSUE THREAD

**Issue by fsat** [hseeberger/scala-sbt#3]
It seems Docker has a built-in character limit - please refer to [Docker Issue #1443](https://github.com/docker/docker/issues/1413).

Because of this, some compilation of the Scala files may fail due length of the filename.

I'm not sure if there's anything could be done about this, but perhaps a mention in the documentation would be helpful.

**Comment by fsat** [comment]
I'll make a fork, update the docs, and do a pull request.

**Comment by hseeberger** [comment]
@fsat, yeah, that sounds like a great plan!
Could you please provide an example of this issue? I never ran into the char limit.

**Comment by byxorna** [comment]
The issue is more a limitation of the docker storage driver. AUFS has a max filename length of 242 (smaller than the 255 limit of most FSes). AUFS is the default storage driver on Ubuntu, and boot2docker. Try setting `-Xmax-classfile-name 240` as a scalac option to work around it.

**Comment by analytically** [comment]
Or use overlay2.
