### ISSUE TITLE
Add docker client to the image?

### ISSUE THREAD

**Issue by htch** [hseeberger/scala-sbt#31]
Hello and thanks for maintaining this image

I use it with all of my CI builds to run tests with testcontainers and to build docker images with sbt-native-packager plugin. Until recently I didn't need to install docker in the image because I could use system docker by mounting it as hostPath volume.
With recent docker updates you can't just mount the docker binary anymore to use it inside a container, so I wonder if it's worthwhile to include docker client binaries with the scala-sbt image? Perhaps it could be a "variant" image ("scala-sbt:docker" or somesuch)?

**Comment by hseeberger** [comment]
Docker inside Docker? Is that possible?
If so, please PR.

**Comment by htch** [comment]
Sort of. I prepared a small demo to explain the idea: https://github.com/htch/scala-docker-build-example
This is the image that I used: https://github.com/htch/scala-sbt-docker/blob/master/Dockerfile
Sure I can make a PR If you think this is a good idea

**Comment by hseeberger** [comment]
Hm ... I‘d rather keep things simple for this image. You could always take it and build your stuff on top, not?

**Comment by htch** [comment]
Alright, this is an option for sure
