### ISSUE TITLE
JDK9

### ISSUE THREAD

**Issue by francisdb** [hseeberger/scala-sbt#33]
Any plans to make JDK 9 and later versions (non-LTS)
http://www.oracle.com/technetwork/java/eol-135779.html

**Comment by hseeberger** [comment]
PR please. BTW, I have also created https://github.com/hseeberger/docker-sbt which is sbt only and smaller in footprint. There's already support for Java 9 in docker-sbt.

**Comment by francisdb** [comment]
`docker-sbt` fits my needs, thanks!
