### ISSUE TITLE
JDK 11

### ISSUE THREAD

**Issue by giorgiovinci** [hseeberger/scala-sbt#52]
We would like to move on the JDK 11.
We're using your image so I've done a pull request with the necessary changes.

**Comment by hseeberger** [comment]
Thanks. PR merged.

**Comment by giorgiovinci** [comment]
Something went wrong and the image was not generated.
Is it just a matter of tagging the commit?
Can you have a look?

**Comment by hseeberger** [comment]
Ah, sorry, I forgot to push the tag. The release should be available within the next minutes.
