### ISSUE TITLE
Slim variant as base image?

### ISSUE THREAD

**Issue by leonardehrenfried** [hseeberger/scala-sbt#55]
Right now version `11.0.1_2.12.8_1.2.7` weighs in at 697 MB. The size is mainly due to the base image.

Each openjdk docker image flavour comes in a "slim" variant which is a lot smaller. That means that only the bare essentials of the Debian packages are installed.

Would you accept a pull request to change the base image to `11.0.1-jdk-slim`? Right now this image weighs in at 330 MB.

**Comment by hseeberger** [comment]
As there are already a lot of (at least more than expected) users of this image, I'm hesitant to this breaking change.

Do you think we could find a way to easily and maybe even automatically have a multidimensional setup that allows us to publish for many/all variants of Java, Scala and sbt?

**Comment by leonardehrenfried** [comment]
I think your concern is reasonable.

If you are willing to burden yourself with the added complexity of the multi-version setup, then I can try and find a solution and send a PR.

On the other hand, another non-invasive solution would be for me to simply maintain a friendly fork of this repo with a slim variant. IMO, not the end of the world to have two repos.

**Comment by gabro** [comment]
Hi, I'm facing the same issue. I've been using this image for a while and I would love a slim/alpine variant as well, since we pull/load this in our CI a lot.

A possible solution for this, would be to have two Dockerfiles, one for the current release and one for the slim/alpine version and setup Dockerhub automated builds for both. @hseeberger, do you think this would work?

**Comment by hseeberger** [comment]
I don't know Dockerhub well enough. If @gabro could put a simple demo how this could work in Dockerhub, we certainly could go that way.

**Comment by gabro** [comment]
Yup, I don't know it very much as well, but I'll give it a try and report back :)

**Comment by hseeberger** [comment]
@gabro any news on this? If so, please reopen.

**Comment by gabro** [comment]
Hey, I ended up rolling my own alpine variant, basically replicating what you've done here. See https://github.com/buildo/scala-sbt-alpine
