### ISSUE TITLE
Github Actions can no longer build scala-sbt:11.0.1_2.12.7_1.2.6

### ISSUE THREAD

**Issue by yodur2potassium** [hseeberger/scala-sbt#56]
Hello.
And first of all thanks for your work on this Docker image, it helps us working with Scala easily :+1: 
As said in title though, Github Actions can no longer build it from sources, starting few days ago but probably unrelated to the new version you provided. There seems to be an error accessing the ScalaSbt or Maven repos involving the ```trustAnchors``` parameter that prevent sbt-1.2.6 being downloaded.
I reproduced locally trying to build from this [tag](https://github.com/hseeberger/scala-sbt/commits/11.0.1_2.12.7_1.2.6).
I'll try to find a fix but I wanted to let you know. [This](https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty?answertab=active#tab-top) seems related to the issue.
Excerpt from the logs:
```
	Server access Error: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.2.6/ivys/ivy.xml

	Server access Error: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/1.2.6/ivys/ivy.xml


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;1.2.6: not found
Error during sbt execution: Error retrieving required libraries
```

**Comment by yodur2potassium** [comment]
Ok, found a quick and dirty fix by adding these lines in your Dockerfile before running the ```curl``` command:
```
# Workaround for cacerts
RUN sed -i 's/pkcs12/jks/' /etc/java-11-openjdk/security/java.security && \
	rm /etc/ssl/certs/java/cacerts && \
	/var/lib/dpkg/info/ca-certificates-java.postinst configure

```
As described in the previously linked StackOverflow thread, it basically change the type of the keystore, wipe it and rebuild from scratch.
Quite radical though but it works!

**Comment by yodur2potassium** [comment]
As I was investigating, I noticed that I can't even build locally from ```master``` because of the same problem.
Do you want me to PR this quick fix?

**Comment by hseeberger** [comment]
Hmmm ... some days ago I build for Java 11.0.1, Scala 2.18.8 and sbt 1.2.7. Take a look here: https://cloud.docker.com/u/hseeberger/repository/docker/hseeberger/scala-sbt

So maybe this is just a problem on your machine?

**Comment by yodur2potassium** [comment]
Yep, saw your new image, tried to build it too but same error on certificates. And I first noticed the problem while the image was built by Github Actions. Did you try to built it with ```--no-cache```?
And I just see, the problem has been solved upwards: https://github.com/docker-library/openjdk/commit/258870647c5a4281c4cc81d0d17b6fd95bcf4141
It was linked to a change 3 days ago on the ```openjdk:11.0.1-jdk``` image you're using.
Probably a goo idea too re-publish your image, their workaround looks cleaner than mine :smile:
You may want to put a CI on to rebuild your image from scratch before publishing, Github Actions do that quite well.
Anyway thanks for your answers and work.
Cheers!

**Comment by hseeberger** [comment]
I let DockerHub build it via automated build: https://cloud.docker.com/repository/docker/hseeberger/scala-sbt/builds

**Comment by yodur2potassium** [comment]
Ok, nice. That was definitely not an error on your side.
https://github.com/docker-library/openjdk/issues/261 is the issue. They missed some automated tests on the certificates and ran on a known Debian bug :slightly_smiling_face: 
Sorry for the trouble

**Comment by tsmgeek** [comment]
This is still an issue
