### ISSUE TITLE
Missing 8u181_2.12.8_1.2.8

### ISSUE THREAD

**Issue by gabro** [hseeberger/scala-sbt#58]
Hi 👋 
Thank you for this image! Would it be possible to publish `8u181_2.12.8_1.2.8`? We use those Scala/Sbt versions with Java 8 and we would like to avoid downloading sbt from scratch in our CI.

Thank you!

**Comment by hseeberger** [comment]
Done.

**Comment by gabro** [comment]
Thank you, Heiko!
