### ISSUE TITLE
building image

### ISSUE THREAD

**Issue by charpov** [hseeberger/scala-sbt#61]
When I build the image myself using the suggested `docker build -t hseeberger/scala-sbt github.com/hseeberger/scala-sbt` and then run it, I get a jshell prompt instead of the bash prompt I get when running the canned image.  I'm new to docker and probably doing something wrong, but what?

**Comment by hseeberger** [comment]
Maybe Java 12?

**Comment by charpov** [comment]
I used the Dockerfile unchanged and I don't have Java 12.  I added a CMD statement at the end to solve the problem, but I was just curious as to why the two behaviors differ.

**Comment by hseeberger** [comment]
The Dockerfile uses Java 11 (not 12) which has the jshell.

**Comment by charpov** [comment]
Yes, and I didn't change that.  Java 11 also has a jshell.

**Comment by hseeberger** [comment]
That‘s what I‘m saying.
