### ISSUE TITLE
PR #63 introduced two regressions

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/scala-sbt#64]
@DaniRey your PR #63 introduced two regressions:
- sbt is no longer "prepared", it needs to download itself on startup
- scala is no longer on the path

I think this is due to still using the directory `root` in some places, e.g. in 
`echo "export PATH=~/scala-$SCALA_VERSION/bin:$PATH" >> /root/.bashrc`.

Could you please take a look and fix that?

**Comment by DaniRey** [comment]
Good catch. I was confused why the non-root user version seemed to behave differently. I'll have a look at it.
