### ISSUE TITLE
non-root user causes image to not be usable on drone

### ISSUE THREAD

**Issue by francisdb** [hseeberger/scala-sbt#67]
introduced by #63 

```
/bin/sh: 3: cannot create /root/.netrc: Permission denied
```
https://discourse.drone.io/t/solved-netrc-permission-denied/171

maybe you could release 2 variants?

**Comment by hseeberger** [comment]
@DaniRey could you please take a look? As I won't release variants I'd rather roll back #63 if we cannot fix this.

**Comment by hseeberger** [comment]
@francisdb thanks for reporting and sorry for the inconvenience.

**Comment by francisdb** [comment]
I wonder what @DaniRey 's use case is where the requirements are to not use a root user

**Comment by francisdb** [comment]
No need to say sorry, these things are hard to foresee, thanks for this repo/docker image! 👍

**Comment by DaniRey** [comment]
@francisdb some companies do not allow to run containers with root. One of this reasons for such policies is, when you have a volume, you are root on that volume, even when the docker container was not started from a root user. You can basically gain additional privileges.

As the `scala-sbt` container is probably mostly used with a volume containing the code/project to be compiled, this is relevant.

I think we can improve the Dockerfile such that everything is installed as `sbtuser` then symlinked for `root`.

This gives the user the opportunity to choose the user with `docker run -u root/sbtuser`. The question that remains is, which one should be default - sbtuser or root.

**Comment by hseeberger** [comment]
@DaniRey thanks for the proposal. As this image has been in use for a long time by many users without an issue, let‘s go for root as the default.
