### ISSUE TITLE
Build for multiple Java base images

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/scala-sbt#71]
There are a lot of PRs upgrading (e.g. to Java 12) or even downgrading (back to Java 8) the Java version. There's also the wish for using a slim variant of the Java base image.

Therefore I'd like to enable the build to support multiple Java base images. Yet I do not know how to achieve that and I'm looking for help.

**Comment by Ksisu** [comment]
I think this article maybe can help: https://medium.com/vaidikkapoor/managing-open-source-docker-images-on-docker-hub-using-travis-7fd33bc96d65
