### ISSUE TITLE
:latest missing

### ISSUE THREAD

**Issue by p-andreas** [hseeberger/scala-sbt#75]
Hi,

I just realized that my automated build failed due to the missing "latest" docker image.

docker pull hseeberger/scala-sbt:latest
Error response from daemon: manifest for hseeberger/scala-sbt:latest not found

**Comment by hseeberger** [comment]
There's no latest any longer due to having a three dimensional (versions for Java, Scala and sbt) build matrix. Please use a tagged version which is a good practice for reproducible builds anyway.

**Comment by hseeberger** [comment]
I agree. A PR with a doc fix would also be nice.
