### ISSUE TITLE
Tag inconsistencies

### ISSUE THREAD

**Issue by myob-geoff-speirs** [hseeberger/scala-sbt#76]
Hi, I had a really weird issue where the docker tags listed in Docker Hub seem wrong. The latest tag listed is `8u212_2.13.0_1.2.8` but when I curl the repository `curl -L -s 'https://registry.hub.docker.com/v2/repositories/hseeberger/scala-sbt/tags?page_size=100'|jq '."results"[]["name"]'` the latest is listed as `8u212_1.2.8_2.13.0`.

When I use the tag `8u212_1.2.8_2.13.0` I can pull, but if I use `latest` or `8u212_2.13.0_1.2.8` it fails.

**Comment by ZorbaDimatteo** [comment]
Hi, I'm having the same issue since yesterday. 
When I try to pull the image without any specific tag I get:
`Error response from daemon: manifest for hseeberger/scala-sbt:latest not found`

**Comment by craigtd** [comment]
Same here - neither `latest` nor  our desired version (`11.0.2_2.12.8_1.2.8`) can be found

**Comment by Hossman333** [comment]
Yeah, same here

**Comment by Hossman333** [comment]
Thanks for this image though! For now we'll just use a specific version.

**Comment by hseeberger** [comment]
There's no more latest – what should that mean with a three dimensional (Java version, Scala version, sbt version) build matrix? Accidentally the version scheme has changed, please use the Docker tags: https://cloud.docker.com/repository/docker/hseeberger/scala-sbt/tags

**Comment by gecube** [comment]
@hseeberger please fix the documentation, because it mentions that one will download image without tag (effectively = `:latest`) and he (she) will get error message as the issue starter.

**Comment by hseeberger** [comment]
@gecube please PR.
