### ISSUE TITLE
Erroring pulling latest release

### ISSUE THREAD

**Issue by clivedsouza1010** [hseeberger/scala-sbt#77]
Getting an error while doing a docker pull of the latest release,

`Error response from daemon: manifest for hseeberger/scala-sbt:8u212_2.13.0_1.2.8 not found`

**Comment by nigredo-tori** [comment]
Looks like the tagging scheme has changed. The image in question is now tagged as `8u212_1.2.8_2.13.0` (note the order of the second and the third versions), and the same goes for other images.

**Comment by ncrothe** [comment]
We were using :latest (I know, I know) and that also stopped working

**Comment by hseeberger** [comment]
There's no more latest – what should that mean with a three dimensional (Java version, Scala version, sbt version) build matrix? Accidentally the version scheme has changed, please use the Docker tags: https://cloud.docker.com/repository/docker/hseeberger/scala-sbt/tags
