### ISSUE TITLE
sbt 1.3.0 image

### ISSUE THREAD

**Issue by francisdb** [hseeberger/scala-sbt#80]
https://www.lightbend.com/blog/sbt-1.3.0-release

**Comment by francisdb** [comment]
thank you!

**Comment by francisdb** [comment]
I was a bit too fast, looks like the images are not available yet @hseeberger ?

**Comment by hseeberger** [comment]
The PR was screwed up, the `vars` file had not been changed. I fixed it and the release should be available soon.

**Comment by NomadBlacky** [comment]
Sorry for sending incomplete P.R.
Thank you for fixing.

Did the last commit fail to build Docker images?
sbt 1.3.0 image not found.

**Comment by hseeberger** [comment]
Yes, ist always falls. I‘m sick of it 😠

**Comment by francisdb** [comment]
maybe you can integrate with travis or similar to test the image build so the PR sender can fix issues?

**Comment by hseeberger** [comment]
I'm lacking time to maintain this increasingly complicated project ...

**Comment by francisdb** [comment]
hard to see what is failing if we get a http 500 on dockerhub for the failed builds

**Comment by francisdb** [comment]
I'd be willing to help out getting this published but would need access to https://cloud.docker.com/u/hseeberger/repository/docker/hseeberger/scala-sbt/timeline?action=04cbe0ba-53b8-41dd-a1ec-8fe7917006c9 (returns 500)

Or is that the issue you are stuck on?

**Comment by francisdb** [comment]
further dicsussion at #84
