### ISSUE TITLE
lmages with GraalVM CE wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [hseeberger/scala-sbt#81]
https://hub.docker.com/r/oracle/graalvm-ce

**Comment by yoohaemin** [comment]
A GraalVM CE image would be nice. However, from what I understand the [license](https://www.oracle.com/downloads/licenses/graalvm-otn-license.html) for GraalVM EE forbids redistributing.

> Oracle grants You a nonexclusive, *nontransferable*, limited license to internally use the Programs, 
> ...
> Further, You may not:
> ...
> * assign this Agreement or *distribute, give, or transfer the Programs*, or any application You develop using the Programs, or an interest in them to any third party, except as expressly permitted in this Agreement for Contractors (the foregoing shall not be construed to limit the rights You may otherwise have with respect to Separately Licensed Third Party Technology);

(emphasis mine)

**Comment by plokhotnyuk** [comment]
@yoohaemin thanks for quoting of the GraalVM EE license

I've removed EE from the request
