### ISSUE TITLE
javac not found, found Java 8 expected 11

### ISSUE THREAD

**Issue by firegate666** [hseeberger/scala-sbt#83]
Hi, I am using the tag 11.0.3_1.2.8_2.12.9 to switch to open JDK 11 from 8
But after installing it, I got confronted by

    java.io.IOException: Cannot run program "javac" (in directory "/www/war/backend"): error=2, No such file or directory

I can't find this one. But what is more surprising is this:

```
war@712acceb888e:/www/war$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1~deb9u1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

**Comment by firegate666** [comment]
I needed to change the path to get it

    export PATH=/usr/local/openjdk-11/bin:$PATH

**Comment by francisdb** [comment]
Are you sure you got the right image?

```
➜  ~ docker run --rm -t hseeberger/scala-sbt:11.0.3_1.2.8_2.12.9 java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment 18.9 (build 11.0.3+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.3+7, mixed mode)
➜  ~ docker run --rm -t hseeberger/scala-sbt:11.0.3_1.2.8_2.12.9 javac -version
javac 11.0.3
```
