### ISSUE TITLE
scala not in $PATH

### ISSUE THREAD

**Issue by b-eyselein** [hseeberger/scala-sbt#89]
When running the images for java 11, sbt 1.3.0 and scala 2.13.x with the following commands:

`docker run -it --rm -u sbtuser -w /home/sbtuser hseeberger/scala-sbt:11.0.4_1.3.0_2.13.1 scala`
or 
`docker run -it --rm -u sbtuser -w /home/sbtuser hseeberger/scala-sbt:11.0.4_1.3.0_2.13.0 scala`

I get the error message that there is no executable found in $PATH for scala. Running those commands as root (without the options `-u` and `-w` does not work either).

Also building another image with these as base images and running `which scala` gives an exit code of 1.

**Comment by francisdb** [comment]
is this a regression compared to previous images?

**Comment by francisdb** [comment]
```
docker run -it --rm -u sbtuser -w /home/sbtuser hseeberger/scala-sbt:11.0.4_1.3.0_2.13.1 /home/sbtuser/scala-2.13.1/bin/scala
```

What would you suggest? Creating a symlink in the user home?

**Comment by b-eyselein** [comment]
You could set $PATH as an ENV-variable in the Dockerfile with

`ENV PATH /home/sbtuser/scala-$SCALA_VERSION/bin:PATH`.

This should be independent of the executed program or the user. You could also remove both echos to `/home/sbtuser/.bashrc`.

**Comment by francisdb** [comment]
I'm updating my pr to do a proper global scala install, no more .bashrc needed

**Comment by francisdb** [comment]
@b-eyselein care to review #90 ?
