### ISSUE TITLE
Latest tag is missing

### ISSUE THREAD

**Issue by Humblehound** [hseeberger/scala-sbt#93]
`docker pull hseeberger/scala-sbt` fails due to the `latest` tag not being present on docker hub.

**Comment by francisdb** [comment]
@hseeberger is there any automation in the pushing of docker images?

**Comment by strokyl** [comment]
+1

**Comment by MaksSieve** [comment]
+100500

**Comment by francisdb** [comment]
you can always propose a pr that would fix this

**Comment by hseeberger** [comment]
There is no more latest. Which one should that be?

**Comment by francisdb** [comment]
the oracle docker image also has multiple versions where they just take some baseline as latest

For quick tests you might not care about what OS you are running on, all you want is a recent scala/sbt version. Personally I would just pick debian / openjdk lts.

For production system use you should of course pick a specific version for reproducibility
